### ISSUE TITLE
Make Feature Request Issue Template

### ISSUE THREAD

**Issue by ghost** [UAceIt-Winter-of-Mentorship/Github-Search-Users-App#1]
Deliverables: Make a nice issue template for the project.

How to make one ? [Resource](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

- Content to be added:
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
**Describe alternatives you've considered**
**Additional context**

**Comment by SangeetaMishra** [comment]
Can I work on this issue?

**Comment by ghost** [comment]
Sure, go for it. please send PR when you are done with it :)

**Comment by SangeetaMishra** [comment]
I have made the PR #2.

**Comment by urvashi-code1255** [comment]
Good work @SangeetaMishra !!
