### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by ghost** [UAceIt-Winter-of-Mentorship/Github-Search-Users-App#4]
Deliverables: Add a nice Pull Request template for the project.

How to make one? [Resource](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

Content to be added: 

## Issue that this pull request solves

 Closes: #276 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

**Comment by SangeetaMishra** [comment]
Can I work on this issue @urvashi-code1255

**Comment by ghost** [comment]
Sure @SangeetaMishra Go for it. Please make a different branch to push your changes :)

**Comment by SangeetaMishra** [comment]
I have made the PR #5.
